FROM alpine:3.19.1

RUN apk add --no-cache \
    openssh \
    iproute2 \
    bash

RUN ssh-keygen -A && \
    echo 'root:admin' | chpasswd && \
    sed -i 's/#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config

EXPOSE 22

# CMD ["/usr/sbin/sshd", "-D"]
