# from alpine distro containing python3
FROM python:3.12-alpine

# retrieve pika package
RUN apk add --no-cache \
    python3-dev \
    py3-pip \
    build-base \
    libffi-dev \
    openssl-dev \
    openssh-client

# install pika
RUN pip install --no-cache-dir paramiko