# Starting image
FROM quay.io/frrouting/frr:10.4.1

# Get opneSSH
RUN apk add --no-cache \
    openssh \
    bash

# setup ssh
RUN ssh-keygen -A && \
    echo 'root:admin' | chpasswd && \
    sed -i 's/#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config

EXPOSE 22

# CMD ["/usr/sbin/sshd", "-D"]
